const String SITE_LIST = 'SITES';
const String NETLIFY_ACCOUNT = 'NETLIFY_ACCOUNT';
const String CMS_LIST = 'CMS_LIST';
const String NODE_RUNNING = 'NODE_RUNNING';
const String NPM_INSTALLED = 'NPM_INSTALLED';
