const String NODE_INSTALLED = 'NODE_INSTALLED';
const String WEBI_INSTALLED = 'WEBI_INSTALLED';
const String HUGO_INSTALLED = 'HUGO_INSTALLED';
const String PKG_MANAGER_INSTALLED = 'PKG_MANAGER_INSTALLED';

const String SET_UP_DONE = 'SET_UP_DONE';
