const String HUGO_INSTALLED = 'HUGO_INSTALLED';
const String WEBI_INSTALLED = 'WEBI_INSTALLED';
const String PKG_INSTALLED = 'PKG_INSTALLED';
const String NODE_INSTALLED = 'NODE_INSTALLED';
const String YARN_INSTALLED = 'NODE_INSTALLED';
const String NETLIFY_INSTALLED = 'NETLIFY_INSTALLED';
const String NETLIFY_LOGGED = 'NETLIFY_LOGGED';

const String SET_UP_DONE = 'SET_UP_DONE';
